INSERT INTO PERSON (ID, BIRTHDAY, NAME) VALUES ('1', '2001-12-05', 'Jonh Doe')
INSERT INTO PERSON (ID, BIRTHDAY, NAME) VALUES ('2', '1997-06-25', 'Mary Kay')

INSERT INTO ADDRESS (ID, CITY, DEFAULT_ADDRESS, NUMBER, PUBLIC_AREA, ZIP_CODE) VALUES('1','Rio de Janeiro','FALSE','35','Estrada do itanhangá','22222-222')
INSERT INTO ADDRESS (ID, CITY, DEFAULT_ADDRESS, NUMBER, PUBLIC_AREA, ZIP_CODE) VALUES('2','Rio de Janeiro','TRUE','333','Rua do Catete','22222-222')
INSERT INTO ADDRESS (ID, CITY, DEFAULT_ADDRESS, NUMBER, PUBLIC_AREA, ZIP_CODE) VALUES('3','Rio de Janeiro','TRUE','33','Rua do Catete','22222-222')

INSERT INTO PERSON_ADDRESS_LIST (PERSON_ID, ADDRESS_LIST_ID) VALUES('1', '1')
INSERT INTO PERSON_ADDRESS_LIST (PERSON_ID, ADDRESS_LIST_ID) VALUES('1', '2')
INSERT INTO PERSON_ADDRESS_LIST (PERSON_ID, ADDRESS_LIST_ID) VALUES('2', '3')